name: Elapsed Time Collector

on:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  workflow_run:
    workflows: ["docs-ecutable - example1","docs-ecutable - Placement","docs-ecutable - Scheduler","docs-ecutable - Mailbox","docs-ecutable - QS","docs-ecutable - Syncer"]
    types:
      - completed
env:
  GH_TOKEN: ${{ secrets.GH_ALL_PROJECT_TOKEN }}

permissions:
  contents: write

jobs:
  elapsed-time-collector:
    name: elapsed-time-collector
    runs-on: ubuntu-latest
    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: echo env
        run: echo "$docs-ecuted-filename"

      - uses: actions/checkout@v3

      - run: git fetch origin main

      - run: make FILENAME="../overrides/placement.txt" write-time-to-file
          
